kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
  namespace:  {{ .Values.namespace }}
data:
  {{- with .Values.data }}
    user: {{ .user | quote }}
    db: {{ .db | quote }}
    pass: {{ .pass | quote }}
  {{- end }}