kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql-pv
